---
# Configuration file for SlugRace: A minigame plugin by BlockHorizons

# Language in which messages are displayed. Available languages:
# en (English), es (Spanish)
language: en

#At what second should the plugin start the countdown title?
title-countdown: 10
...